version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: yarn test
  auto_deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Auto Deploy
          command: ./bin/release
workflows:
  version: 2
  commit:
    jobs:
      - test
  autodeploy:
    jobs:
      - test
      - auto_deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - test
