version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  auto_deploy:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Auto Deploy
          command: bin/release

workflows:
  version: 2
  commit:
    - test
  autodeploy:
    jobs:
      - test
      - auto_deploy
    triggers:
      - schedule:
          cron: "0 14 * * 1-5"  # UTC -4 is 10AM (daylight savings)
          filters:
            branches:
              only: master

