# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  auto_deploy:
    docker:
      - image: circleci/node:10
    - run:
        name: Auto Deploy
        command: bin/release
workflows:
  version: 2


  autodeploy:
    jobs:
      # REACT FRONTEND
      - build
      - auto_deploy: *default_auto_deploy

    triggers:
      - schedule:
          cron: "0 14 * * 1-5"  # UTC -4 is 10AM (daylight savings)
          filters:
            branches:
              only: master

